// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamingServerService.proto

package org.example.streaming.streamingserverservice;

public interface StreamServerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.streaming.StreamServerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
