// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamingServerService.proto

package org.example.streaming.streamingserverservice;

public interface StreamServerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.streaming.StreamServerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serverName = 1;</code>
   */
  java.lang.String getServerName();
  /**
   * <code>string serverName = 1;</code>
   */
  com.google.protobuf.ByteString
      getServerNameBytes();
}
