// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamingServerService.proto

package org.example.streaming.streamingserverservice;

public interface UnaryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.streaming.UnaryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
